name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.nvim-versions }}

    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.5"

    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        make prepare

    - name: Run linter
      run: luacheck lua/ 

    - name: Run tests
      run: |
        make vendor
        make test

